version: '2'
services:
  mysql:
    image: mysql:5.7.28
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'fec_images'
      MYSQL_USER: 'root'